---
- name: Update Proxmox Hosts
  hosts: proxmox
  become: yes
  user: root

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      register: apt_update_result

    - name: Upgrade all packages if updates are available
      apt:
        upgrade: dist
      when: apt_update_result.changed

    - name: Remove unnecessary packages if updates are available
      apt:
        autoremove: yes
      when: apt_update_result.changed

    - name: Check if a reboot is needed
      command: "[ -f /var/run/reboot-required ]"
      changed_when: false
      register: reboot_required
      ignore_errors: true

    - name: Notify handler to reboot
      meta: flush_handlers
      when: reboot_required.rc == 0

  handlers:
    - name: Reboot the system
      reboot: