- name: Update Ubuntu
  hosts: ubuntu
  remote_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      register: apt_update_result

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Remove unnecessary packages
      apt:
        autoremove: yes

    - name: Check if a reboot is needed
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Trigger reboot if needed
      debug:
        msg: "Reboot required"
      when: reboot_required.stat.exists
      notify: Reboot the system

  handlers:
    - name: Reboot the system
      reboot:
