---
    - name: Ensure aptitude is present (for dependency resolution)
      ansible.builtin.apt:
        name: aptitude
        state: present
        update_cache: true

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 # Cache valid for 1 hour to avoid redundant updates

    - name: Wait for a few seconds (adjust as needed)
      ansible.builtin.wait_for:
        timeout: 30  # Wait for 10 seconds

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - net-tools
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - gnupg-agent
          - autoconf
          - dpkg-dev
          - file
          - g++
          - gcc
          - libc-dev
          - make
          - pkg-config
          - re2c
          - wget
          - git
          - nfs-common
          - nano
          - qemu-guest-agent
        state: present
        update_cache: true

    - name: Create mount point directory
      ansible.builtin.file:
        path: /mnt/NAS  # Replace with the desired mount point
        state: directory

    - name: Mount NFS share  
      ansible.builtin.mount:
        src: "{{ nfs_server }}:/mnt/nas/Backups"  # Replace with the NFS server and share path
        path: /mnt/NAS  # Replace with the mount point
        fstype: nfs
        opts: defaults
        state: mounted

    - name: Start qemu-guest-agent service
      systemd:
        name: qemu-guest-agent
        state: started
      tags:
        - start

    - name: Enable qemu-guest-agent service for auto-start
      systemd:
        name: qemu-guest-agent
        enabled: yes
      tags:
        - enable