---

  - name: Clone > Set VM Config > Power On
    ansible.builtin.command:
      cmd: "pwsh -File {{ script_path }} -NodeFQDN {{ node_fqdn }} -Name {{ Name }} -VMID {{ VMID }} -Node {{ Node }} -password '{{ pwsh_password }}' -memory {{ memory }} -sockets {{ sockets }} -ipconfig0 {{ ipconfig0 }} -ipconfig1 {{ ipconfig1 }} -net1 {{ net1 }} -Username {{ Username }} -TokenName {{ TokenName }} -Token {{ Token }}"
    register: script_output
    changed_when: "'Changes made' in script_output.stdout"
    failed_when: "'Error' in script_output.stderr"
    no_log: false

  - name: Display "Clone > Set VM Config > Power On" Output
    debug:
      msg: "{{ script_output.stdout }}"

#- name: Include "Update System" Playbook
#  import_playbook: ../task/Update-System.yml

#- name: Include "Stage Docker Install" Playbook
#  import_playbook: ../task/Stage-DockerInstall.yml
