---
- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu/ {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
  notify: Restart Docker  # Notify the handler if Docker is installed or updated

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ Docker_User }}"
    groups: docker
    append: yes

- name: Install Docker module for Python
  ansible.builtin.pip:
    name: docker

- name: Install latest Docker Compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Create Docker-Compose symlink (if necessary)
  ansible.builtin.file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link
    force: no

#- name: Add private registry (if needed)
#  ansible.builtin.template:
#    src: daemon.j2
#    dest: /etc/docker/daemon.json
#    mode: '0644'

