---
- name: Prep and deploy PSRunner.
  hosts: localhost
  gather_facts: no
  #become: true
  vars_files:
    - /authorized-keys/secrets.yml
    #- vars/secrets.yml
    #- vars/TUS-PUDNODE01_vars.yml
  roles:
    - ansible_prereqs
    - Deploy_PSRunner

- name: Configure PSRunner.
  hosts: PSrunner
  gather_facts: yes
  become: true
  vars_files:
    - /authorized-keys/secrets.yml
    #- vars/secrets.yml
    #- vars/TUS-PUDNODE01_vars.yml
  roles:
   - Configure_PSRunner

- name: Deploy VM from clone. Set VM parameters. Power On.
  hosts: PSrunner
  gather_facts: yes
  vars_files:
    - /authorized-keys/secrets.yml
    #- vars/secrets.yml
    #- vars/TUS-PUDNODE01_vars.yml
  become: true
  roles:
    - Deploy_VM

- name: Configure VM w/ Docker.
  hosts: PROD_DOCKER
  gather_facts: yes
  become: true
  vars_files:
    - /authorized-keys/secrets.yml
    #- vars/secrets.yml
    #- vars/TUS-PUDNODE01_vars.yml
  roles: 
    - Configure_VM-WithDocker
    